# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3

        environment:
          - ES_ADDRESS: "localhost:9200"
          - GIT_NAME: "circleci"
          - GIT_BRANCH: "circleci"

      - image: elasticsearch:6.8

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - run: npm test